### ISSUE TITLE
Sync prepare in progress... nothing happens

### ISSUE THREAD

**Issue by smorhaim** [lukasz-wronski/vscode-ftp-sync#39]
I set up the sftp settings as shown below, started a Remote to Local Sync... nothing happens. 
The message Sync prepare in progress... shows below, but nothing gets synced. It is a very small remote folder with 10 small files. The RSA key does work, since it is the same key I use for all my SSH and other apps. 

(Using RSA key , replaced some values for privacy)
Settings
{
    "remotePath": "./path...",
    "host": "ip...",
    "username": "user...",
    "password": "",
    "port": 22,
    "protocol": "sftp",
    "uploadOnSave": true,
    "passive": false,
    "debug": false,
    "privateKeyPath": "/path/to/my/key",
    "ignore": [
        "\\.vscode",
        "\\.git"
    ]
}

![image](https://cloud.githubusercontent.com/assets/7375949/13529471/69bc5f30-e1ea-11e5-8a05-a98e0aaf1159.png)

**Comment by mattrat** [comment]
That is the same behavior I was getting. I assumed it was due to the RSA key. 
https://github.com/lukasz-wronski/vscode-ftp-sync/issues/35

**Comment by smorhaim** [comment]
I am sure the key works, has no passphrase and it has the right permissions. It has to be some bug.

**Comment by jakenuts** [comment]
I got the same with a small error in my config file, perhaps there is a console where more logging can be shown?

**Comment by tbjerstedt-hol** [comment]
I am having same problem. I am running on a MAC with OS X El Capitan. 

And there is a console - Menubar > Help > Toggle Developer Tools, Console Window shows:
> [Plugin Host] Error: Encrypted private key detected, but no passphrase given
>     at Client.connect (/Users/tbjerstedt/.vscode/extensions/lukasz-wronski.ftp-sync-0.3.1/node_modules/ssh2/lib/client.js:151:15)
>     at self.connect (/Users/tbjerstedt/.vscode/extensions/lukasz-wronski.ftp-sync-0.3.1/modules/sftp-wrapper.js:19:16)
>     at connect (/Users/tbjerstedt/.vscode/extensions/lukasz-wronski.ftp-sync-0.3.1/modules/sync-helper.js:175:7)
>     at Object.prepareSync (/Users/tbjerstedt/.vscode/extensions/lukasz-wronski.ftp-sync-0.3.1/modules/sync-helper.js:198:2)
>     at prepareSync (/Users/tbjerstedt/.vscode/extensions/lukasz-wronski.ftp-sync-0.3.1/modules/sync-command.js:53:19)
>     at /Users/tbjerstedt/.vscode/extensions/lukasz-wronski.ftp-sync-0.3.1/modules/sync-command.js:111:4
>     at Object.p [as _notify] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/pluginHostProcess.js:5:11292)
>     at Object.__dirname.undefined.L.enter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/pluginHostProcess.js:5:14454)
>     at __dirname.undefined.t.Class.define._run (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/pluginHostProcess.js:5:16280)
>     at __dirname.undefined.t.Class.define._completed (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/pluginHostProcess.js:5:15721)

If I run SFTP from the shell, it is able to connect.

**Comment by BradyOsborne** [comment]
I too am having the same problem.  I'm not evening using a key and it's still having the problem.  :(

**Comment by abrahamaranda** [comment]
Same here.
Any news/help about this problem?
:(

**Comment by arescec** [comment]
Same

**Comment by dadagama** [comment]
same issue here

**Comment by mdiaATarinc** [comment]
Having the same issue while syncing remote to local on a pretty small directory. I see the message 
"Ftp-sync: sync prepare in progress..." for a long time and the remote contents don't appear in the explorer sidebar.

**Comment by b9sk** [comment]
When my internet connection was corrupted for a while (3G throttling or some else) I have same issue. Seems like there is no command to abort preparing (like a timeout option or a special command in console). So, i just restart VS Code for resolving the issue.

It happens not often, only when server is not responding.

**Comment by Caffeinaation** [comment]
Having the same issue from time to time :(
Any fixes?

**Comment by skrzepij** [comment]
Same issue here.. 
Anything changes? 

I'm using same SFTP settings (privateKey and passphrase) like I was used in remote-sync plugin for Atom. Also I have no problem with login to my server through SSH. 

I think this is quite important issue.. 
Right now my config looks like this: 
```
{
    "remotePath": "/var/www/path/to/public_html",
    "host": "192.168.1.12",
    "username": "Username",
    "port": 1234,
    "secure": false,
    "protocol": "sftp",
    "uploadOnSave": true,
    "passive": false,
    "debug": false,
    "privateKeyPath": "/path/to/.ssh/id_dsa",
    "passphrase": "passToTheKey",
    "ignore": [
        "\\.vscode",
        "\\.git",
        ".DS_Store",
        "Thumbs.db",
        ".sublime-(project|workspace)",
        "sftp-config(-alt\\d?)?\\.json",
        "sftp-settings.json",
        ".remote-sync.json",
        "/venv/**",
        ".svn",
        ".hg/**",
        ".bzr",
        "_darcs",
        "CVS",
        "desktop.ini",
        "tmp",
        "log",
        "**/node_modules/**",
        "Oldskel/**",
        "**/vendors/**",
        ".tmp/**",
        "\\.idea"
    ],
    "generatedFiles": {
        "uploadOnSave": false,
        "extensionsToInclude": [],
        "path": ""
    }
}
```

**Comment by mohitdia** [comment]
I have moved on to ftp-simple since. It has been working great for me.

**Comment by skrzepij** [comment]
Ok in my case the problem occurred due to properties in `ignore` array.
You cannot use double `*` symbol. 

So i had to change my `ignore` file list:
```
      "\\.vscode",
      "\\.git",
      "\\.DS_Store",
      "\\.sublime-(project|workspace)",
      "sftp-config(-alt\\d?)?\\.json",
      "sftp-settings.json",
      "/venv/*",
      ".svn",
      ".hg/*",
      ".bzr",
      "_darcs",
      "CVS",
      ".DS_Store",
      "Thumbs.db",
      "desktop.ini",
      ".samsung-cache",
      "tmp",
      "log",
      "node_modules",
      "Oldskel",
      "vendors",
      ".remote-sync.json",
      ".tmp",
      ".idea"
```

And for now it's working, even with `uploadOnSave` option turned on. 

But I think there should be shown some error, because I had no clue this can be caused of my config file structure.

**Comment by MatthewGieger** [comment]
Can anyone confirm that the above solution works?

**Comment by blakemotl** [comment]
Yeah I had the same issue. It was due to a * in my config ignore list. As soon as I removed it, it started working again.

**Comment by parinpshah94** [comment]
You just need to use [".csv"] to ignore a specific file type here. The solution above worked for me too.

**Comment by meichthys** [comment]
@lukasz-wronski I believe we can close this issue!

**Comment by Vincetroid** [comment]
It's still happening, I tested without ** and what @parinpshah94  and doesn't work
