### ISSUE TITLE
Running the contributed command:'extension.ftpsyncupload' failed. With no debug information

### ISSUE THREAD

**Issue by abos5** [lukasz-wronski/vscode-ftp-sync#98]
Running the contributed command:'extension.ftpsyncupload' failed. With no debug information
Can't figure out why, here is my configuration:
```json
{
    "remotePath":  "/home/xxx/",
    "host": "foo.bar",
    "username": "xxx",
    "port": 22,
    "protocol": "sftp",
    "uploadOnSave": true,
    "passive": true,
    "debug": true,
    "privateKeyPath": "C:\\Users\\xxx\\.ssh\\xxx.ppk",
    "ignore": [
        "\\.vscode",
        "\\.git",
    ]
}
```

![image](https://cloud.githubusercontent.com/assets/5197118/19638877/74bc2f56-9a08-11e6-8f84-0ec914ef54b5.png)

**Comment by abos5** [comment]
Turns out it is OK to sync file to my VPS, and the error occurs when I click this:
![image](https://cloud.githubusercontent.com/assets/5197118/19639942/24e30284-9a0d-11e6-8e56-fc85755ccfa2.png)

**Comment by imanilchaudhari** [comment]
I'm having the same problem too

**Comment by rip3rs** [comment]
hmmm I had an issue like this and found out that my .vscode folder (settings) was not in my root of the project folder, rather it was on a subfolder of the project

**Comment by Shulin** [comment]
I'm actually running into this issue too. I think it started happening with a recent VSCode update.

Won't upload on save and manually trying to select 'Local to Remote' fails.

@rip3rs My .vscode file is in the root.

Multiple restarts of the laptop and VSCode didn't help. ='(

**Comment by dschoerk** [comment]
same problem like @Shulin

**Comment by duongphuhiep** [comment]
même message but different error

[2018-08-17 15:29:26.712] [exthost1] [error] TypeError: Cannot read property 'fsPath' of undefined
    at module.exports (C:\Users\hduong\extensions\lukasz-wronski.ftp-sync-0.3.3\modules\uploadcurrent-command.js:14:13)
    at C:\Users\hduong\.vscode\extensions\lukasz-wronski.ftp-sync-0.3.3\extension.js:32:158
    at e._executeContributedCommand (d:\prg\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:712:994)
    at e.$executeContributedCommand (d:\prg\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:713:479)
    at e._doInvokeHandler (d:\prg\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:671:983)
    at e._invokeHandler (d:\prg\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:671:701)
    at e._receiveRequest (d:\prg\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:670:767)
    at e._receiveOneMessage (d:\prg\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:670:536)
    at d:\prg\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:669:452
    at d:\prg\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:672:575
    at d:\prg\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:96:903
    at e.fire (d:\prg\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:98:218)
    at a (d:\prg\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:162:713)
    at Socket._socketDataListener (d:\prg\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:162:932)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20) extension.ftpsyncuploadselected

**Comment by dschiller** [comment]
Any Solutions ?
